version: '3.7'
services:
    app:
        build:
            context: ./docker/php
        ports:
            - 8000:80
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        container_name: app_todolist
        volumes:
            - .:/var/www/html
            - ./docker/apache/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
            - ./docker/apache/sites:/etc/apache2/sites-enabled
        networks:
            - mynetwork

networks:
    mynetwork:

volumes:
    db-data:
        driver: local